/**
 * Generate Skill Icon Data
 *
 * Extracts only the icons actually used in skills.ts from the simple-icons
 * package, producing a small static lookup file. This avoids bundling all
 * 3,300+ simple-icons to the client (5MB uncompressed) when only ~36 are needed.
 *
 * Output: src/data/generated/skill-icon-data.ts
 *
 * Usage: npx tsx scripts/generate-skill-icons.ts
 *        npm run generate:skill-icons
 */

import * as fs from "fs";
import * as path from "path";
import * as simpleIcons from "simple-icons";

const PROJECT_ROOT = path.join(__dirname, "..");
const SKILLS_FILE = path.join(PROJECT_ROOT, "src/data/skills.ts");
const OUTPUT_FILE = path.join(PROJECT_ROOT, "src/data/generated/skill-icon-data.ts");

/**
 * Extract all unique iconSlug values from skills.ts by regex.
 * Avoids importing TypeScript source (which may use path aliases).
 */
function extractIconSlugs(): string[] {
  const content = fs.readFileSync(SKILLS_FILE, "utf-8");
  const slugs = new Set<string>();
  const regex = /iconSlug:\s*"([^"]+)"/g;
  let match;

  while ((match = regex.exec(content)) !== null) {
    slugs.add(match[1]);
  }

  return [...slugs].sort();
}

/**
 * Look up a simple-icons icon by slug.
 * simple-icons exports named constants like siTypescript, siReact, etc.
 */
function findIconBySlug(slug: string): { title: string; slug: string; path: string; hex: string } | null {
  for (const value of Object.values(simpleIcons)) {
    if (value && typeof value === "object" && "slug" in value && (value as { slug: string }).slug === slug) {
      const icon = value as { title: string; slug: string; path: string; hex: string };
      return { title: icon.title, slug: icon.slug, path: icon.path, hex: icon.hex };
    }
  }
  return null;
}

function main(): void {
  console.log("Generating skill icon data...\n");

  const slugs = extractIconSlugs();

  if (slugs.length === 0) {
    console.error("Error: No iconSlug values found in skills.ts");
    process.exit(1);
  }

  console.log(`Found ${slugs.length} icon slugs in skills.ts\n`);

  let foundCount = 0;
  let missingCount = 0;
  const entries: string[] = [];

  for (const slug of slugs) {
    const icon = findIconBySlug(slug);

    if (icon) {
      foundCount++;
      // Escape any backticks or backslashes in the SVG path
      const safePath = icon.path.replace(/\\/g, "\\\\").replace(/`/g, "\\`");
      entries.push(
        `  "${slug}": {\n    title: "${icon.title}",\n    slug: "${slug}",\n    hex: "${icon.hex}",\n    path: "${safePath}",\n  },`
      );
      console.log(`  ✓ ${slug} → ${icon.title}`);
    } else {
      missingCount++;
      console.log(`  ✗ ${slug} → NOT FOUND in simple-icons (custom icon?)`);
    }
  }

  // Write output file
  const output = `/**
 * Auto-generated skill icon data — DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/generate-skill-icons.ts
 * Source: simple-icons package (build-time only)
 * Icons: ${foundCount} entries extracted from ${slugs.length} slugs in skills.ts
 *
 * This file replaces the runtime import of all 3,300+ simple-icons.
 * Only icons actually referenced in skills.ts are included.
 */

import type { SkillIconData } from "@/lib/skill-icons";

// prettier-ignore
export const SIMPLE_ICON_DATA: Record<string, SkillIconData> = {
${entries.join("\n")}
};
`;

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_FILE, output, "utf-8");

  // Summary
  console.log("\n" + "=".repeat(50));
  console.log(`Generated: ${foundCount}/${slugs.length} icons`);

  if (missingCount > 0) {
    console.log(`Missing: ${missingCount} slug(s) not in simple-icons (expected for custom icons)`);
  }

  console.log(`Output: ${OUTPUT_FILE}`);
  console.log("\nDone!");
}

main();
